---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/tests/{userId}/{restrictId}":
    get:
      tags:
      - test-controller
      operationId: getUserRoles
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: restrictId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Role"
components:
  schemas:
    Role:
      type: object
      properties:
        roleId:
          type: integer
          format: int64
        name:
          type: string
