  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/openjdk:11.0.3-jdk-stretch 
      steps:
        - checkout # check out the code in the project directory
        - run: echo "athanprodcaster Mohammad Tofic Mohammad" # run the `echo` command
        #- run: mvn clean package -DskipTests=true  -Dmaven.test.skip=true 
        #- run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
        #- run: ./build/buildAll.sh
        - run: docker image ls
    PushToDockerHub:
      docker:
        - image: circleci/java:11
          auth:
            username: happyml
            password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout
        - setup_remote_docker
            version: 19.03.13
            docker_layer_caching:true
        - run: |
            docker build -t happyml/athanprodcaster:latest ./AuthorizationService
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docekr push happyml/athanprodcaster:latest
   workflows:
     version: 2
     build_and_push:
       jobs:
         - build
         - PushToDockerHub         
         
  